# Generated by Django 5.0.6 on 2024-06-06 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='store.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='store.cart')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=225, null=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('payment_mode', models.CharField(choices=[('KHALTI', 'KHALTI'), ('COD', 'COD')], max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('INDELIVERY', 'INDELIVERY'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.customer')),
            ],
        ),
    ]
