# Generated by Django 5.0.6 on 2024-06-07 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
